services:
  db:
    image: postgres:16-alpine
    container_name: oficina_db_container
    environment:
      POSTGRES_USER: user_oficina
      POSTGRES_PASSWORD: password_oficina
      POSTGRES_DB: oficina_db

    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/seed.sql:docker-entrypoint-initdb.d/2-seed.sql

  volumes: 
    postgres_data